// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChLDuDx9Clg0H4dU-NuDagYJHoWlU7ogQ',
    appId: '1:104515210923:web:3f7dfaa8ee72dcf5a4f1ee',
    messagingSenderId: '104515210923',
    projectId: 'windu-s-database',
    authDomain: 'windu-s-database.firebaseapp.com',
    storageBucket: 'windu-s-database.firebasestorage.app',
    measurementId: 'G-6LXG42P526',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf9kbGJhiUERIxHkWyfC3GrMK5iMJM8fo',
    appId: '1:104515210923:android:63fd73a613a0b54ba4f1ee',
    messagingSenderId: '104515210923',
    projectId: 'windu-s-database',
    storageBucket: 'windu-s-database.firebasestorage.app',
  );
}
